# ----------------------------
# Configurazioni
# ----------------------------

# ====================
#    Setting Data
# ====================
global_heading: 0
goal: [20, 20]
cell_length: 0.5

# Movement data
rotation_speed: 0.5

movement_distance: 0.5
movement_speed: 0.3

# LIDAR DATA
angle: 0.5760

# IR costant
k: 3.37

use_sim_time: true